config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "kittens#index"
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
    validates :cuteness, inclusion:  { in:1..10 }
    validates :softness, inclusion:  { in:1..10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
    def index
        @kittens = Kitten.all
        respond_to do |format|
            format.json {render :json => @kittens}
        end
    end

    def new
        @kitten = Kitten.new
    end

    def create
        @kitten = Kitten.new(kitten_params)
        if @kitten.save
            redirect_to @kitten, notice: "You've created a new kitten, meow!"
        else
            render :new, status: :unprocessable_entity 
        end
    end

    def show
        @kitten = Kitten.find(params[:id])
        respond_to do |format|
            format.json {render :json => @kitten}
        end
    end

    def edit
        @kitten = Kitten.find(params[:id])
    end

    def update
        @kitten = Kitten.find(params[:id])
        if @kitten.update(kitten_params)
            redirect_to @kitten, notice: "You've updated your kitten!"
        else
            flash.alert = "Your cat is too cute or too soft"
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @kitten = Kitten.find(params[:id])
        @kitten.destroy
        redirect_to root_path, notice: "You've deleted your kitten :("
    end


    private
    
    def kitten_params
        params.require(:kitten).permit(:name, :age,:cuteness,:softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: @kitten do |f| %>
    <%= f.label(:name, 'Name')%>
    <%= f.text_field(:name) %>
    <%= f.label(:age, 'Age')%>
    <%= f.number_field(:age) %>
    <%= f.label(:cuteness, 'Cuteness')%>
    <%= f.number_field(:cuteness) %>
    <%= f.label(:softness, 'Softness')%>
    <%= f.number_field(:softness) %>
    <%= f.submit%>
<% end %>

app/views/kittens/edit.html.erb
<% flash.each do |type, msg| %>
  <div id='flash'>
    <%= msg %>
  </div>
<% end %>
<h1>Edit Kitten</h1>
<%= render partial:'form' %>

app/views/kittens/index.html.erb
<% flash.each do |type, msg| %>
  <div id='flash'>
    <%= msg %>
  </div>
<% end %>
<h1>Kittens</h2>
<br>
<% @kittens.each do |kitten| %>
<div id='kitten'>
    <p>Name: </p>
    <%= kitten.name %>
    <p>Age: </p>
    <%= kitten.age %>
    <%= link_to 'See more', kitten_path(kitten.id) %>
    <%= link_to 'Delete', kitten_path(kitten.id),  data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
</div>
<% end %>

app/views/kittens/new.html.erb
<% flash.each do |type, msg| %>
  <div id='flash'>
    <%= msg %>
  </div>
<% end %>
<h1>New Kitten</h1>
<%= render partial:'form' %>

app/views/kittens/show.html.erb
<% flash.each do |type, msg| %>
  <div id='flash'>
    <%= msg %>
  </div>
<% end %>
<h1><%= @kitten.name%> </h2>
<br>
<div id='kitten'>
    <p>Age: </p>
    <%= @kitten.age %>
    <p>Cuteness: </p>
    <%= @kitten.cuteness %>
    <p>Softness: </p>
    <%= @kitten.softness %>
    <%= link_to 'Edit', edit_kitten_path(@kitten.id) %>
    <%= link_to 'Delete', kitten_path(@kitten.id),  data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>